# Emojis texto plano
emojis_texto_plano = [
    [":)", "sonrisa"],
    [":(", "triste"],
    [";)", "guiño"],
    [":3", "tierno"],
    [":D", "riendo"],
    ["xD", "carcajadas"],
    [":'(", "llorando"],
    [":')", "llorando de felicidad"],
    ["<3", "corazón"],
    ["u.u", "apenado"],
    [":/", "molesto"],
    ["e_e", "mirando de reojo"],
    ["*.*", "maravillado"],
    ["-.-'", "vergüenza"],
    ["-.-", "enfadado"],
    ["lol", "carcajada"],
    ["Lol", "carcajada"],
    [":l", "incómodo"],
]

emojis_con_diseno = [
    ["👌", "ok"],
    ["🔫", "pistola de agua"],
    ["👽", "alien"],
    ["🐶", "cara de perro"],
    ["😭", "cara llorando"],
    ["✔️","marca de verificación"],
    ["😁", "cara que ríe con los ojos sonrientes"],
    ["😉", "guiño"],
    ["😍", "cara con ojos de corazón"],
    ["🙏", "manos de oración"],
    ["🎤", "micrófono"],
    ["😝", "cara con la lengua de fuera y los ojos apretados"],
    ["❤️","corazón rojo"],
    ["😏", "cara de mirada pícara"],
    ["💋", "marca de beso"],
    ["😃", "cara sonriente con ojos grandes"],
    ["😔", "cara de tristeza"],
    ["♥","traje de corazón"],
    ["😆", "cara sonriente con ojos cerrados"],
    ["♡", "corazón transparente"],
    ["♫", "signo de música"],
]
